version: "3"

services:
    nginx:
        environment:
            - API_HOST
            - REACT_HOST
        image: nginx
        restart: unless-stopped
        volumes:
            - ngnix-config:/etc/nginx/templates
        ports:
            - "80:80"
        networks: 
            ltsnet:
                ipv4_address: "192.168.240.2"

    sjnode:
        build: ./
        restart: always
        environment:
            ENVIRONMENT: production
        networks: 
            ltsnet:
                ipv4_address: "192.168.240.3"

volumes:
    ngnix-config:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: "${NGINX_TEMPLATES_PATH}"


networks: 
    ltsnet:
        driver: bridge
        ipam:
            config:
                - subnet: "192.168.240.0/24"
